# Generated by Django 3.2.10 on 2021-12-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=45)),
                ('tag', models.CharField(max_length=12)),
                ('idioma', models.CharField(max_length=9)),
                ('usoTotal', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ('-usoTotal',),
                'managed': True,
            },
        ),
    ]
